//
//  AniListConstants.m
//  MAL Library
//
//  Created by 小鳥遊六花 on 4/2/18.
//  Copyright © 2018 Atelier Shiori. All rights reserved.
//

#import "AniListConstants.h"

@implementation AniListConstants
NSString *const kAnilisttoMALId = @"query ($id: Int!, $type: MediaType) {\n  Media(id: $id, type: $type) {\n    id\n    idMal\n  }\n}";
NSString *const kMALtoAniListId = @"query ($id: Int!, $type: MediaType) {\n  Media(idMal: $id, type: $type) {\n    id\n    idMal\n  }\n}";
NSString *const kAnilistTitleIdInformation = @"query ($id: Int!, $type: MediaType) {\n  Media(id: $id, type: $type) {\n    id\n    idMal\n    title {\n      romaji\n      english\n      native\n      userPreferred\n    }\n    startDate {\n      year\n      month\n      day\n    }\n    endDate {\n      year\n      month\n      day\n    }\n    coverImage {\n      large\n      medium\n    }\n    bannerImage\n    format\n    type\n    status\n    episodes\n    duration\n    chapters\n    volumes\n    description\n    averageScore\n    popularity\n    genres\n    synonyms\n    source\n    isAdult\n    relations {\n      edges {\n        relationType\n        node {\n          id\n          title {\n            romaji\n            english\n            native\n          }\n          type\n          coverImage {\n            large\n          }\n        }\n      }\n    }\n    tags {\n      id\n      name\n      description\n      category\n      rank\n      isGeneralSpoiler\n      isMediaSpoiler\n      isAdult\n    }\n    rankings {\n      id\n      rank\n      type\n      format\n      year\n      season\n      allTime\n      context\n    }\n  }\n}\n\n";
NSString *const kAnilistCurrentUsernametoUserId = @"{\n  Viewer {\n    id\n    name\n    mediaListOptions {\n      scoreFormat\n    }\n  }\n}";
NSString *const kAnilistanimeList = @"query ($id : Int!, $page: Int) {\n  AnimeList: Page (page: $page) {\n    mediaList(userId: $id, type: ANIME) {\n      id :media{id}\n      entryid: id\n      title: media {title {\n        title: userPreferred\n      }}\n      episodes: media{episodes}\n      duration: media{duration}\n      image_url: media{coverImage {\n        large\n        medium\n      }}\n        type: media{format}\n      status: media{status}\n      score: score(format: POINT_100)\n      watched_episodes: progress\n      watched_status: status\n      rewatch_count: repeat\n      private\n      notes\n      watching_start: startedAt {\n        year\n        month\n        day\n      }\n      watching_end: completedAt {\n        year\n        month\n        day\n      }\n    }\n    pageInfo {\n      total\n      currentPage\n      lastPage\n      hasNextPage\n      perPage\n    }\n  }\n}";
NSString *const kAnilistmangaList = @"query ($id : Int!, $page: Int) {\n  MangaList: Page (page: $page) {\n    mediaList(userId: $id, type: MANGA) {\n      id :media{id}\n      entryid: id\n      title: media {title {\n        title: userPreferred\n      }}\n      chapters: media{chapters}\n      volumes: media{volumes}\n      image_url: media{coverImage {\n        large\n        medium\n      }}\n      type: media{format}\n      status: media{status}\n      score: score(format: POINT_100)\n      read_chapters: progress\n      read_volumes: progressVolumes\n      read_status: status\n      reread_count: repeat\n      private\n      notes\n      read_start: startedAt {\n        year\n        month\n        day\n      }\n      read_end: completedAt {\n        year\n        month\n        day\n      }\n    }\n        pageInfo {\n      total\n      currentPage\n      lastPage\n      hasNextPage\n      perPage\n    }\n  }\n}";
NSString *const kAnilistreviewbytitleid = @"query ($id: Int!, $page: Int) {\n  Page (page: $page) {\n    reviews (mediaId: $id){\n      id\n      body(asHtml: true)\n      rating\n      ratingAmount\n      createdAt\n      updatedAt\n      user {\n        id\n        name\n        avatar {\n          large\n        }\n      }\n    }\n        pageInfo {\n      total\n      currentPage\n      lastPage\n      hasNextPage\n      perPage\n    }\n  }\n}";
NSString *const kAnilisttitlesearch = @"query ($query: String, $type: MediaType) {\n  Page(perPage: 50) {\n    media(search: $query, type: $type) {\n      id\n      title {\n        userPreferred\n        romaji\n      }\n      coverImage {\n        medium\n        large\n      }\n      format\n      type\n      status\n      episodes\n      chapters\n      volumes\n      isAdult\n    }\n  }\n}";
NSString *const kAnilistcharacterslist = @"query ($id: Int!, $page: Int = 1) {\n  Media(id: $id, type: ANIME) {\n    id\n    characters(page: $page, sort: [ROLE]) {\n      pageInfo {\n        total\n        perPage\n        hasNextPage\n        currentPage\n        lastPage\n      }\n      edges {\n        node {\n          id\n          name {\n            first\n            last\n          }\n          image {\n            medium\n            large\n          }\n        }\n        role\n        voiceActors {\n          id\n          name {\n            first\n            last\n            native\n          }\n          image {\n            medium\n            large\n          }\n          language\n        }\n      }\n    }\n  }\n}";
NSString *const kAniliststafflist = @"query ($id: Int!, $page: Int = 1) {\n  Media(id: $id, type: ANIME) {\n    id\n    staff(page: $page, sort:[ROLE]) {\n       pageInfo {\n        total\n        perPage\n        hasNextPage\n        currentPage\n        lastPage\n      }\n      staff:edges {\n        person:node {\n          id\n          name {\n            first\n            last\n            native\n          }\n        }\n      }\n    }\n  }\n}";
NSString *const kAnilistpersonbyid = @"query ($name: String) {\n  User (name: $name) {\n    id\n    name\n    mediaListOptions {\n      scoreFormat\n    }\n }\n}";
NSString *const kAnilistUserProfileByUsername = @"query ($name: String) {\n  User (name: $name) {\n    id\n    name\n    about # (asHtml: true)\n    donatorTier\n    isFollowing\n    avatar {\n      large\n      medium\n    }\n    updatedAt\n  }\n}";
@end
